# Site settings
name: Bits of deutsche Paella
description: 'Coding in English, thinking in Spanish, living in Germany'

baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://blog.jdonado.com' # the base hostname & protocol for your site

# Build settings
markdown:            kramdown
relative_permalinks: false
permalink:           :title/

pagination:          false
paginate:            8
paginate_path:       page/:num/

author:
    name: 'F. Javier R. Donado'
    email: 'jdonado@jdonado.com'
    uri: 'http://www.jdonado.com'

sass:
    sass_dir: _sass
    style:    compressed

defaults:
  -
      scope:
        path: '_posts'
        type: 'posts'
      values:
        reading_time: true
        # Meta
        show_tags: true
        show_categories: true
        # Social
        share_buttons: true
        disqus: true

gems:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - run.sh
  - build.sh
  - docs
  - README.md
  - old
