version: '2'
services:
  blog:
    image: httpd:2.4
    container_name: blog
    volumes:
      - ./docs:/usr/local/apache2/htdocs/
    restart: "always"
    environment:
      - VIRTUAL_HOST=blog.jdonado.com
      - LETSENCRYPT_EMAIL=jdonado@jdonado.com
      - LETSENCRYPT_HOST=blog.jdonado.com
    networks:
      - jdonado-nw
    expose:
      - 8888

networks:
   jdonado-nw:
     external:
       name: jdonado-nw
